# hooks:
#   all:
#     pre:
#       - type: oidc
#         provider: aws
#         role_arn: "arn:aws:iam::104300641251:role/terrateam"

# For Checkov checks
workflows:
  - tag_query: ""
    plan:
      - type: init
      - type: plan
      - type: env
        name: CKV_SKIP_CHECK_CKV_AWS
        cmd: ["echo", "CKV_AWS*"]
        name: CKV_SKIP_CHECK_CKV2_AWS
        cmd: ["echo", "CKV2_AWS*"]
      - type: run
        cmd: ["checkov-wrapper"]
        capture_output: true
# For OPA policy checks
# workflows:
#   - tag_query: ""
#     plan:
#       - type: init
#       - type: plan
#       - type: env
#         name: CHECKOV_POLICIES
#         cmd: ["echo", "$TERRATEAM_ROOT/AWS-S3/policy/"]
#       - type: run
#         cmd: ["conftest-wrapper"]
#         capture_output: true
